apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: fit-tracker-system
  labels:
    app.kubernetes.io/name: fit-tracker
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  DB_USERNAME: fit-tracker
  DB_PASSWORD: secret
