apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: fit-tracker-system
  labels:
    app.kubernetes.io/name: fit-tracker
    app.kubernetes.io/component: backend
data:
  DB_URL: jdbc:postgresql://postgres:5432/fit-tracker
