CREATE TABLE exercise (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    muscle_group VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    description VARCHAR(1000)
);

CREATE TABLE workout (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    notes VARCHAR(1000)
);

CREATE TABLE workout_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_workout_entry_workout
        FOREIGN KEY (workout_id)
        REFERENCES workout (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_workout_entry_exercise
        FOREIGN KEY (exercise_id)
        REFERENCES exercise (id),
    CONSTRAINT chk_workout_entry_sets_positive CHECK (sets > 0),
    CONSTRAINT chk_workout_entry_reps_positive CHECK (reps > 0),
    CONSTRAINT chk_workout_entry_weight_non_negative CHECK (weight >= 0)
);

CREATE INDEX idx_workout_date ON workout (date DESC);
CREATE INDEX idx_workout_entry_workout_id ON workout_entry (workout_id);
CREATE INDEX idx_workout_entry_exercise_id ON workout_entry (exercise_id);
