apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fit-tracker-system
  labels:
    app.kubernetes.io/name: fit-tracker
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app: postgres
    app.kubernetes.io/name: fit-tracker
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
