apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fit-tracker-system
  labels:
    app.kubernetes.io/name: fit-tracker
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: fit-tracker
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: fit-tracker
