name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            fcvetkovski4/fit-tracker-backend:latest
            fcvetkovski4/fit-tracker-backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            fcvetkovski4/fit-tracker-frontend:latest
            fcvetkovski4/fit-tracker-frontend:${{ github.sha }}
